export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_ERROR = "FETCH_SCHEDULE_ERROR";

export const FETCH_SCHEDULE_FROM_CACHE = "FETCH_SCHEDULE_FROM_CACHE";
export const FETCH_SCHEDULE_FROM_CACHE_SUCCESS =
  "FETCH_SCHEDULE_FROM_CACHE_SUCCESS";
export const FETCH_SCHEDULE_FROM_CACHE_ERROR =
  "FETCH_SCHEDULE_FROM_CACHE_ERROR";

export const RECONNECT = "RECONNECT";
export const RECONNECT_SUCCESS = "RECONNECT_SUCCESS";
export const RECONNECT_ERROR = "RECONNECT_ERROR";
