export const FETCH_SCHEDULE_TIME = "FETCH_SCHEDULE_TIME";
export const FETCH_SCHEDULE_TIME_SUCCESS = "FETCH_SCHEDULE_TIME_SUCCESS";
export const FETCH_SCHEDULE_TIME_ERROR = "FETCH_SCHEDULE_TIME_ERROR";
